services:
  postgres:
    image: postgres:17-alpine
    container_name: shortly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shortly
      POSTGRES_USER: shortly
      POSTGRES_PASSWORD: shortly
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shortly-redis
    restart: unless-stopped
    ports:
      - '6379:6379'

volumes:
  postgres_data:
