/**
 * Integration tests for the URL repository.
 *
 * These tests interact with the real PostgreSQL database rather than
 * mocking the database client. This allows us to verify that the SQL
 * queries and database mappings work correctly.
 *
 * The tests use unique short codes so they do not conflict with existing
 * application data.
 */
import { afterAll, afterEach, describe, expect, it } from 'vitest'

import { db } from '../../infrastructure/postgres/client.js'

import {
  createUrl,
  findAllUrls,
  findUrlByIdWithClicks,
  findClickHistory,
  findUrlByShortCode,
} from './url.repository.js'

describe('URL repository', () => {
  /**
   * Keep track of IDs created by the tests so they can be removed after
   * each test. This prevents the integration tests from polluting the
   * development database.
   */
  const createdUrlIds: bigint[] = []

  /**
   * Remove test records after every test.
   *
   * click_events references urls with ON DELETE CASCADE, so deleting the
   * URL also removes any associated click events.
   */
  afterEach(async () => {
    for (const id of createdUrlIds) {
      await db.query(
        `
          DELETE FROM urls
          WHERE id = $1
        `,
        [id.toString()],
      )
    }

    createdUrlIds.length = 0
  })

  /**
   * Close the PostgreSQL connection pool after all repository tests finish.
   *
   * Without this, Vitest may keep running because the PostgreSQL pool
   * still has open connections.
   */
  afterAll(async () => {
    await db.end()
  })

  describe('createUrl', () => {
    /**
     * Verifies that createUrl inserts a URL into PostgreSQL and correctly
     * maps the returned database row into a UrlRecord.
     */
    it('creates and returns a URL record', async () => {
      /**
       * Use a unique short code so this test does not conflict with
       * URLs already present in the database.
       */
      const shortCode = `test-${Date.now()}`

      /**
       * The repository expects the ID to be generated by the service.
       *
       * We use a value from the PostgreSQL sequence so the test behaves
       * consistently with the real application.
       */
      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      /**
       * Keep track of the inserted URL so afterEach can clean it up.
       */
      createdUrlIds.push(id)

      const createdUrl = await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/test',
        expiresAt: null,
      })

      /**
       * Verify that the database record was mapped correctly.
       */
      expect(createdUrl.id).toBe(id)
      expect(createdUrl.shortCode).toBe(shortCode)
      expect(createdUrl.originalUrl).toBe('https://example.com/test')
      expect(createdUrl.expiresAt).toBeNull()

      /**
       * createdAt and updatedAt are generated by PostgreSQL, so we only
       * need to verify that they contain valid Date objects.
       */
      expect(createdUrl.createdAt).toBeInstanceOf(Date)
      expect(createdUrl.updatedAt).toBeInstanceOf(Date)
    })
  })

  describe('findUrlByShortCode', () => {
    /**
     * Verifies that a URL can be retrieved using its short code.
     */
    it('finds a URL by short code', async () => {
      const shortCode = `find-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/find-test',
        expiresAt: null,
      })

      const url = await findUrlByShortCode(shortCode)

      /**
       * Verify that the repository returns the expected URL.
       */
      expect(url).not.toBeNull()
      expect(url?.id).toBe(id)
      expect(url?.shortCode).toBe(shortCode)
      expect(url?.originalUrl).toBe('https://example.com/find-test')
      expect(url?.expiresAt).toBeNull()
    })

    /**
     * Verifies that the repository returns null when the short code
     * does not exist.
     */
    it('returns null when the short code does not exist', async () => {
      const url = await findUrlByShortCode(`does-not-exist-${Date.now()}`)

      expect(url).toBeNull()
    })
  })

  describe('findAllUrls', () => {
    /**
     * Verifies that findAllUrls returns URLs even when they have no
     * associated click events.
     *
     * The repository uses a LEFT JOIN, so URLs without clicks should
     * still appear in the result with a click count of zero.
     */
    it('returns URLs with zero clicks', async () => {
      const shortCode = `list-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/list-test',
        expiresAt: null,
      })

      const urls = await findAllUrls()

      const url = urls.find((item) => item.id === id)

      /**
       * The URL should be present even though no click events exist.
       */
      expect(url).toBeDefined()

      expect(url?.shortCode).toBe(shortCode)
      expect(url?.originalUrl).toBe('https://example.com/list-test')
      expect(url?.clicks).toBe(0)
      expect(url?.status).toBe('active')
    })

    /**
     * Verifies that findAllUrls correctly calculates the number of
     * click events associated with a URL.
     */
    it('returns the correct click count', async () => {
      const shortCode = `clicks-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/click-test',
        expiresAt: null,
      })

      /**
       * Insert three click events for the URL.
       *
       * These are inserted directly into the database because this test
       * is specifically verifying that findAllUrls counts database
       * records correctly.
       */
      await db.query(
        `
          INSERT INTO click_events (url_id)
          VALUES ($1), ($1), ($1)
        `,
        [id.toString()],
      )

      const urls = await findAllUrls()

      const url = urls.find((item) => item.id === id)

      expect(url).toBeDefined()
      expect(url?.clicks).toBe(3)
      expect(url?.status).toBe('active')
    })

    /**
     * Verifies that an URL whose expiry date has passed is reported
     * as expired.
     */
    it('marks expired URLs correctly', async () => {
      const shortCode = `expired-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/expired-test',
        expiresAt: new Date(Date.now() - 60_000),
      })

      const urls = await findAllUrls()

      const url = urls.find((item) => item.id === id)

      expect(url).toBeDefined()
      expect(url?.status).toBe('expired')
    })

    /**
     * Verifies that a URL with a future expiry date is reported
     * as active.
     */
    it('marks URLs with a future expiry as active', async () => {
      const shortCode = `active-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/active-test',
        expiresAt: new Date(Date.now() + 60 * 60 * 1000),
      })

      const urls = await findAllUrls()

      const url = urls.find((item) => item.id === id)

      expect(url).toBeDefined()
      expect(url?.status).toBe('active')
    })
  })

  describe('findUrlByIdWithClicks', () => {
    /**
     * Verifies that a URL can be retrieved by its database ID and that
     * the associated click events are correctly counted.
     */
    it('finds a URL by ID with its click count', async () => {
      const shortCode = `by-id-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/by-id-test',
        expiresAt: null,
      })

      /**
       * Create two click events for this URL.
       *
       * The repository should aggregate these events and return
       * clicks: 2.
       */
      await db.query(
        `
          INSERT INTO click_events (url_id)
          VALUES ($1), ($1)
        `,
        [id.toString()],
      )

      const url = await findUrlByIdWithClicks(id)

      /**
       * Verify that the URL was found and its fields were mapped correctly.
       */
      expect(url).not.toBeNull()
      expect(url?.id).toBe(id)
      expect(url?.shortCode).toBe(shortCode)
      expect(url?.originalUrl).toBe('https://example.com/by-id-test')

      /**
       * Verify that the click count was calculated from click_events.
       */
      expect(url?.clicks).toBe(2)

      /**
       * A URL without an expiry date should be active.
       */
      expect(url?.status).toBe('active')
    })

    /**
     * Verifies that the repository returns null when the requested
     * URL ID does not exist.
     *
     * The service layer is responsible for converting this null result
     * into a 404 API error.
     */
    it('returns null when the URL ID does not exist', async () => {
      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const nonExistentId = BigInt(row.id)

      const url = await findUrlByIdWithClicks(nonExistentId)

      expect(url).toBeNull()
    })
  })

  describe('findClickHistory', () => {
    /**
     * Verifies that click events are grouped by their UTC calendar date
     * and that multiple clicks on the same day are counted together.
     */
    it('groups clicks by day', async () => {
      const shortCode = `history-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/history-test',
        expiresAt: null,
      })

      /**
       * Insert three clicks on the same UTC date.
       *
       * The repository should combine these into one data point with
       * a click count of three.
       */
      await db.query(
        `
          INSERT INTO click_events (url_id, clicked_at)
          VALUES
            ($1, '2026-08-20 10:00:00+00'),
            ($1, '2026-08-20 14:00:00+00'),
            ($1, '2026-08-20 18:00:00+00')
        `,
        [id.toString()],
      )

      const history = await findClickHistory(id)

      expect(history).toEqual([
        {
          date: '2026-08-20',
          clicks: 3,
        },
      ])
    })

    /**
     * Verifies that clicks occurring on different dates are returned
     * as separate data points.
     */
    it('returns separate entries for different days', async () => {
      const shortCode = `history-days-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/history-days-test',
        expiresAt: null,
      })

      /**
       * Create clicks across three different UTC dates.
       *
       * The expected result should contain one entry per day.
       */
      await db.query(
        `
          INSERT INTO click_events (url_id, clicked_at)
          VALUES
            ($1, '2026-08-20 10:00:00+00'),
            ($1, '2026-08-20 14:00:00+00'),
            ($1, '2026-08-21 10:00:00+00'),
            ($1, '2026-08-22 10:00:00+00'),
            ($1, '2026-08-22 18:00:00+00')
        `,
        [id.toString()],
      )

      const history = await findClickHistory(id)

      /**
       * The repository should return the dates in chronological order.
       */
      expect(history).toEqual([
        {
          date: '2026-08-20',
          clicks: 2,
        },
        {
          date: '2026-08-21',
          clicks: 1,
        },
        {
          date: '2026-08-22',
          clicks: 2,
        },
      ])
    })

    /**
     * Verifies that a URL with no click events returns an empty history.
     */
    it('returns an empty array when there are no clicks', async () => {
      const shortCode = `history-empty-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/history-empty-test',
        expiresAt: null,
      })

      const history = await findClickHistory(id)

      expect(history).toEqual([])
    })

    /**
     * Verifies that click events are grouped using their UTC calendar
     * date rather than the local timezone of the application server.
     *
     * The first click below is late on August 20 in UTC but may fall
     * on August 21 in an Indian timezone. The repository should use
     * the UTC date because that is what its SQL explicitly specifies.
     */
    it('groups click events using UTC dates', async () => {
      const shortCode = `history-utc-${Date.now()}`

      const { rows } = await db.query<{ id: string }>(
        `SELECT nextval('urls_id_seq') AS id`,
      )

      const row = rows[0]

      if (!row) {
        throw new Error('Failed to generate test URL ID')
      }

      const id = BigInt(row.id)

      createdUrlIds.push(id)

      await createUrl({
        id,
        shortCode,
        originalUrl: 'https://example.com/history-utc-test',
        expiresAt: null,
      })

      /**
       * These timestamps fall on different UTC dates.
       *
       * The second timestamp is also August 21 in India, while the first
       * remains August 20 in India. This verifies that the repository
       * explicitly groups events according to UTC rather than application
       * server timezone.
       */
      await db.query(
        `
          INSERT INTO click_events (url_id, clicked_at)
          VALUES
            ($1, '2026-08-20 23:30:00+00'),
            ($1, '2026-08-21 00:30:00+00')
        `,
        [id.toString()],
      )

      const history = await findClickHistory(id)

      expect(history).toEqual([
        {
          date: '2026-08-20',
          clicks: 1,
        },
        {
          date: '2026-08-21',
          clicks: 1,
        },
      ])
    })
  })
})
